Splat/PlatformModeDetector.cs

added string to match:
Microsoft.VisualStudio.QualityTools.UnitTestFramework

Support MsTest in VS2013

---

Rebracer.xml

In the interests of maintaining the existing style, this PR simply adds rebracer settings (taken from those in RxUI).

Add rebracer settings.

---

Splat/PlatformModeDetector.cs

Recognize NCrunch as a test runner.

---

Splat/Logging.cs

This PR fixes #104 by removing the `suppressLogging` field and related logic.

Removes the suppressLogging field

---

README.md

docs
readme out of date following #159 

update readme to match new target platforms

---

README.md

use correct github status badge from appveyor

---

LICENSE
src/Directory.build.props
src/Directory.build.targets
src/Splat/Splat.csproj

Ship v4.0.1

---

azure-pipelines.yml

Update and rename .azure-pipelines.yml to azure-pipelines.yml

---

version.json

Splat version 6.0
Version 5.3
version 6.0
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

Release Splat version 6.0

---

src/Splat/Platforms/WinRT/Bitmaps/PlatformBitmapLoader.cs

fixes #144 
That EXIF images look garbled if they are rotated. Eg on Nokia devices.
That we handle rotating the image correctly.
Shouldn't, only be if the decoder indicates there is rotation.
This is based on work from @jspuij and in closed PR #145

fix: Support for EXIF rotated bitmaps

---

src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs

fixes #168
Null reference exception
No exception
Nothing

fix: Android bitmap loader exception

---

README.md

Documentation of the new dependency resolver packages.
No documentation on the README.
Package information on the README.
Nothing.

documentation: Added dependency resolver packages to README

---

README.md
src/Splat.DryIoc/README.md

- Added DryIoc Readme to main Readme
README for Splat.DryIoc
There is no README for Splat.DryIoc
There is a README for Splat.DryIoc and a link from the main README and Badges for packages.
README as packages have not been published to NuGet.

housekeeping: Added Splat.DryIoc README

---

README.md

restructured locator documentation as per the stack overflow question.
moved the sub packages into the service locator section of the readme
#265 developer experience 
nothing

bug: locator documentation

---

src/Splat.NLog/Splat.NLog.csproj

Fixes #256 so that we get better Xamarin targetting.

housekeeping: Update NLog to 4.5.7

---

azure-pipelines.yml

- Now using a azure template for handling our building.

housekeeping: Add a template for azure building

---

cake.config

Adds a Cake configuration file to ensure that the Splat build script will execute consistently on any machine regardless of the Cake specific environment variables that exist.
With my Cake global environment variables the build script fails to find the tools that were downloaded for the execution.
The Splat Cake script executes regardless of my environment variables.
The build.

housekeeping: Added cake.config

---

README.md
src/Splat.Autofac/README.md

Adds Splat.Autofac README
There is no README
There is a README
Nothing

housekeeping: Added Splat.Autofac README

---

README.md

Adds new package information to README

housekeeping: Updating README with Splat 7.0.1 packages

---

src/Splat.Autofac/Splat.Autofac.csproj
src/Splat.DryIoc/Splat.DryIoc.csproj
src/Splat.Ninject/Splat.Ninject.csproj
src/Splat.SimpleInjector/Splat.SimpleInjector.csproj

Added package descriptions for the Splat adapters
There is not package description.
There is a package description.
Nothing.

housekeeping: Added package descriptions for Splat adapters

---

src/Directory.build.props
src/Splat.Log4Net/Splat.Log4Net.csproj
src/Splat.Microsoft.Extensions.Logging/Splat.Microsoft.Extensions.Logging.csproj
src/Splat.NLog/Splat.NLog.csproj
src/Splat.Serilog/Splat.Serilog.csproj
src/Splat/Splat.csproj

Changes owner reference to Anaïs Betts and author to Dot Net Foundation.
NA - Non functional change.
NA - Non functional change.
NA - Non functional change.
NA - Non functional change.

Housekeeping: Updated references to DotNet Foundation

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/Colors/KnownColorTests.cs
src/Splat.Tests/Colors/SplatColorTests.cs
src/Splat.Tests/Logging/WrappingFullLoggers/ConsoleLoggerTests.cs
src/Splat.Tests/TargetFrameworkExtensionsTests.cs
src/Splat/Logging/ConsoleLogger.cs
src/Splat/Logging/WrappingLogLevelLogger.cs

Add a console logger which will send the output to the console.

feature: Add a console logger and log level prefix wrapper

---

README.md

Added information about initializing ReactiveUI when using Splat Adapters.

housekeeping: Updated README.MD

---

src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs
src/Splat.Microsoft.Extensions.DependencyInjection/SplatMicrosoftExtensions.cs

fix: reuse resolver instead of re-instantiating it

---

README.md
src/Splat.Autofac/README.md
src/Splat.DryIoc/README.md
src/Splat.Microsoft.Extensions.DependencyInjection/README.md
src/Splat.Ninject/README.md

docs update
Related: https://github.com/reactiveui/website/pull/346

housekeeping: updated MSDI docs

---

src/Splat.Android.Tests/Resources/Resource.Designer.cs
src/Splat.Drawing/PlatformModeDetector.cs
src/Splat.Tests/API/ApiApprovalTests.SplatUIProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatUIProject.netcoreapp2.2.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatUIProject.netcoreapp3.0.approved.txt

Adds a way to override the platform mode detector.

fix: Missing override for platform mode detector

---

src/Splat.Autofac/README.md

Just a quick typo fix Splay=>Splat
Splay
Splat
Nothing

Fixed Typo Splay=>Splat

---

src/Splat/TargetFrameworkExtensions.cs

Add new platforms to the platform detector.

feature: add new target frameworks

---

README.md

The load method does not seem to support byte array.
docs update

housekeeping: Update README.md

---

README.md

Updates Splat logo in README.md. Additionally, a minor formatting issue is fixed.
Currently, there is the old Splat image in README.md.
Now, we use the new icon from the [styleguide](https://github.com/reactiveui/styleguide) repository.
Nothing.

Update Logo and fix formatting

---

build.config
src/Directory.build.props

This updates Cake to 0.38.1 and Stylecop Analyzer to 1.2.0-beta.164

housekeeping: Update stylecop analyzer

---

version.json

Housekeeping: Release Splat 9.5.x

---

src/Splat.SimpleInjector/SplatSimpleInjectorExtensions.cs

Fix method summary.
Replace ``AutoFac`` with ``Simpleinjector`` in method summary.

Method summary: replace AutoFac with Simpleinjector 

---

.github/workflows/ci-build.yml

This PR incorporates the changes from https://github.com/reactiveui/ReactiveUI.Validation/pull/156
Apparently, there is no issues with `codecov` in this repository, but probably worth using the same `yml` template anyway?

housekeeping: Use newer Github Actions setup

---

README.md

Signed-off-by: Michael Schnerring <3743342+schnerring@users.noreply.github.com>
Added reference to Simple Injector README
Missing reference

Add reference to Simple Injector README

---

version.json

Release: 11.1

---

.github/workflows/codeql-analysis.yml

This adds the github action for code security scanning
n/a
embedded scanning on github security tab
n/a

housekeeping: add codeql analysis

---

src/Splat.Common.Test/IViewModelOne.cs
src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs
src/Splat.SimpleInjector/SimpleInjectorDependencyResolver.cs
src/Splat.Tests/API/ApiApprovalTests.SplatProject.net5.0.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp3.1.approved.txt
src/Splat.Tests/LocatorSerialRegisterTests.cs
src/Splat.Tests/ServiceLocation/BaseDependencyResolverTests.cs
src/Splat.Tests/Splat.Tests.csproj
src/Splat/ServiceLocation/DependencyResolverMixins.cs
src/Splat/ServiceLocation/FuncDependencyResolver.cs
src/Splat/ServiceLocation/ModernDependencyResolver.cs
src/Splat/ServiceLocation/ResolverMixins.cs

RegisterAnd allows serial registration or chaining.
feature and tests
Registration must be done individually.
Registration can be done by chaining the registrations with RegisterAnd ending with a Register
none

feature and tests RegisterAnd

---

src/Benchmarks/CurrentBenchmark.cs
src/Benchmarks/CurrentMutableBenchmark.cs
src/Benchmarks/DependencyResolver.cs
src/Benchmarks/LocatorBenchmark.cs
src/Benchmarks/Program.cs
src/Benchmarks/Splat.Benchmarks.csproj

update
benchmark is not setup for current project status
updated setup
N/A

Update Benchmark tests

---

src/Splat.Drawing/Splat.Drawing.csproj

update
N/A
N/A
none
reference clean up

Remove direct references and use reference assemblies for .net 4.x

---

src/ReactiveUI.DI.Tests/NinjectReactiveUIDependencyTests.cs
src/ReactiveUI.DI.Tests/ReactiveUI.DI.Tests.csproj
src/Splat.Raygun/RaygunFeatureUsageTrackingSession.cs
src/Splat.Raygun/Splat.Raygun.csproj

fix
build is failing
fix build
non expected
update Mindscape.Raygun4Net.NetCore

fix build and test

---

.github/workflows/release.yml

Use GitHub environments to authorise releases

housekeeping: Use environment for releases

---

src/Directory.build.props

Revert "Add support for reproducible builds"

---

src/Splat.Tests/API/ApiApprovalTests.cs

Removes the pragma in the test script to bring in line with coding standards.

housekeeping: Remove pragma

---

src/Directory.build.targets
src/Splat.Drawing/Platforms/ServiceLocationDrawingInitialization.cs

Fix registration outside of SharedLibraries

---

src/Directory.build.props
src/Splat.Drawing/Splat.Drawing.csproj
src/Splat.Microsoft.Extensions.DependencyInjection.Tests/MicrosoftDependencyResolverTests.cs
src/Splat.Microsoft.Extensions.DependencyInjection/Splat.Microsoft.Extensions.DependencyInjection.csproj
src/Splat.NLog/Splat.NLog.csproj
src/Splat.Tests/LocatorTests.cs

Fix
Xamarin.Mac cannot locate libs due to issue with VS
Manual path added for Xamarin.Mac
none

Fix for Xamarin.Mac issue

---

src/Directory.build.props
src/Splat.AppCenter/Splat.AppCenter.csproj
src/Splat.Drawing/Splat.Drawing.csproj
src/Splat.DryIoc/Splat.DryIoc.csproj
src/Splat.Exceptionless/Splat.Exceptionless.csproj
src/Splat.Microsoft.Extensions.DependencyInjection/Splat.Microsoft.Extensions.DependencyInjection.csproj
src/Splat.Microsoft.Extensions.Logging/MicrosoftExtensionsLogProvider.cs
src/Splat.Microsoft.Extensions.Logging/Splat.Microsoft.Extensions.Logging.csproj
src/Splat.NLog/Splat.NLog.csproj
src/Splat.Serilog/Splat.Serilog.csproj
src/Splat.Tests/Logging/WrappingFullLoggers/MicrosoftExtensionsLoggingLoggerTests.cs
version.json

Update
MonoAndroid12.0 (SDK 31)
MonoAndroid12.1 (SDK 32)
Building with SDK 32

Update MonoAndroid to V12.1 (SDK 32)

---

.github/workflows/ci-build.yml
.github/workflows/release.yml
src/Splat.Drawing/Splat.Drawing.csproj

Housekeeping
Xamarin.Mac patch in use
Use latest VS2022
Remove Xamarin.Mac patch
Update API tests
none

Housekeeping Update API Tests remove Xamarin.Mac patch

---

version.json

Housekeeping : Update minor version

---

src/Directory.build.props
src/Splat.Avalonia.Autofac/Splat.Avalonia.Autofac.csproj
src/Splat.Avalonia.DryIoc/Splat.Avalonia.DryIoc.csproj
src/Splat.Avalonia.DryIoc1.Tests/Splat.Avalonia.DryIoc1.Tests.csproj
src/Splat.Avalonia.DryIoc2.Tests/Splat.Avalonia.DryIoc2.Tests.csproj
src/Splat.Avalonia.Microsoft.Extensions.DependencyInjection/Splat.Avalonia.Microsoft.Extensions.DependencyInjection.csproj
src/Splat.Avalonia.Microsoft1.Tests/Splat.Avalonia.Microsoft1.Tests.csproj
src/Splat.Avalonia.Microsoft2.Tests/Splat.Avalonia.Microsoft2.Tests.csproj
src/Splat.Avalonia.Ninject/Splat.Avalonia.Ninject.csproj
src/Splat.Avalonia.Tests/Splat.Avalonia.Tests.csproj
src/Splat.Drawing.Tests/API/ApiApprovalTests.cs
src/Splat.Drawing/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs
src/Splat.Drawing/Platforms/ServiceLocationDrawingInitialization.cs
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet6_0.verified.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet7_0.verified.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet8_0.verified.txt
src/Splat.Tests/API/ApiApprovalTests.cs
src/Splat/ApplicationPerformanceMonitoring/EnableFeatureUsageTrackingExtensions.cs
src/Splat/Disposables/CompositeDisposable.cs
src/Splat/ExceptionMixins.cs
src/Splat/Logging/FullLoggerExtensions.cs
src/Splat/Logging/LogManagerMixin.cs
src/Splat/Logging/WrappingPrefixLogger.cs
src/Splat/Properties/AssemblyInfo.cs
src/Splat/ServiceLocation/DependencyResolverMixins.cs
src/Splat/ServiceLocation/Locator.cs
src/Splat/ServiceLocation/ModernDependencyResolver.cs
src/Splat/ServiceLocation/ResolverMixins.cs
src/Splat/ServiceLocation/ServiceLocationInitialization.cs
src/global.json

Fix for Verify.Xunit
Update Avalonia version
Verify.Xunit and Avalonia versions are not the latest
updating Verify.Xunit requires code fixes to enable build
Verify.Xunit and Avalonia versions are updated
Avalonia will need to be migrated to the latest version.

Fix for Verify.Xunit, Update Avalonia version

---

src/Directory.Packages.props
src/Splat.sln

Update
Xunit version too low for new packages
Updated Xunit
none expected

Housekeeping Update Packages to resolve build

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet8_0.verified.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet9_0.verified.txt
src/Splat/Builder/AppBuilder.cs

Feature
Introduces the AppBuilder class to configure an application without reflection, supporting AOT environments. Provides methods for module registration, custom actions, and resolver selection, enabling flexible dependency resolver configuration.
New Feature

Add AppBuilder for AOT-compatible setup

---

README.md

Docs
Expanded the README with detailed instructions and examples for configuring Splat using the AppBuilder and IModule pattern, including AOT-friendly setup, external container integration, and extensibility. This helps users avoid reflection and improve compatibility with trimming and ahead-of-time compilation scenarios.
N/A

Add AppBuilder and IModule usage documentation
