Splat/PlatformModeDetector.cs

I was getting a false positive since I had a reference to WriteableBitampEx.WinRt.
I was under the impression that I had removed this before in the ReactiveUI project...

Removes Pex from IsUnitTestRunner

---

Splat/TypeForwardedSystemDrawing.cs

I think this is in the right place in the #ifdef

.NET 4.5 Fix for MethodNotFoundException when constructing a System.Drawing.Color using a KnownColor

---

Splat/Colors/Color.cs

For System.Drawing.Color to be useful cross platform, I need to be able to persist instances in my mobile app.
This works OK in my .NET 4.5 unit tests because System.Drawing.Color is redirected to the .NET framework version. On Windows phone however the Splat implementation is used, which doesn't have the appropriate mark up to allow serialization. I've added DataContract markup, which allows the value property to serialize correctly. The Color Name does not serialize, because it only gets populated when using the constructor that takes a KnownColor of a known name. I don't think this really matters though, as it is the value that is the important piece of data.

Marked up System.Drawing.Color as a DataContract so that it can be serialized

---

Splat/Logging.cs

Hey Paul,
First ever github PR.  Just going to guess how this works, let me know what all I screwed up... I'll catch on quick.
I'm using Splat in a project. The project includes an exported COM object to implement IDTExtensibility2 blahblahblah Office blahblahblah COM. Ran into the issue that if I "implement" IEnableLogger on that exposed COM object itself, the typelib converter gets mad that Splat isn't registered with COM:
> :x: 3 The assembly 'Splat, Version=1.6.1.0, Culture=neutral, PublicKeyToken=null' is not registered for COM Interop. Please register it with regasm.exe /tlb.
> :x: 4 The assembly "D:\Projects\foo\bin\Local Debug\bar.dll" could not be converted to a type library. Type library exporter encountered an error while processing 'Baz.Connect, Baz'. Error: Error loading type …

Hide IEnableLogger from COM to allow ComVisible-classes to still log with Splat

---

Splat/Cocoa/Bitmaps.cs
Splat/Splat-XamarinMac.csproj

This PR fixes the Xamarin.Mac project so it builds. I also confirmed that mono touch still builds. Don't have a Xam.iOS license, so can't be 100% certain I didn't mess that one up.

Attempt to fix #117 (Xam.Mac Unified w/o dependency on System.Drawing)

---

Splat/WinRT/Bitmaps.cs

This is necessary for applications that are a share target and want to
load images while being a share target, as the share window gets its own
dispatcher.

If available, use the dispatcher for the current thread on WinRT

---

Splat/PlatformModeDetector.cs

Pull the call to ToUpperInvariant out of the inner loop into the outer
loop so it's only called once per assembly

Make the assembly lookup in the ModeDetector more efficient

---

Splat/Points/Point.cs
Splat/Points/PointF.cs
Splat/Points/Rectangle.cs
Splat/Points/RectangleF.cs
Splat/Points/Size.cs
Splat/Points/SizeF.cs

Implementation of the IEquatable<T> to avoid boxing as suggested by the
.NET guidelines (8.6)

Implement IEquatable<T>

---

Splat/Xaml/Bitmaps.cs

System.Uri constructor without UriKind parameter creates a UriKind.Absolute Uri but local bitmap resources may require a Uri of type UriKind.Relative. Thus adding the UriKind.RelativeOrAbsolute parameter in Xaml version of PlatformBitmapLoader.LoadFromResource.
I couldn't get the function to work with embedded resources on WP8 app without this modification.

Enable also relative URI in Xaml Bitmap PlatformBitmapLoader.LoadFromResource

---

Splat/ServiceLocation.cs

Supersedes #113 by ensuring values are of the generic type.

IMutableDependencyResolver mixins

---

Splat/MemoizingMRUCache.cs

This avoids the duplicate lookup of the dictionary entry

Use Dictionary.TryGetValue in the MemoizingMRUCache where possible

---

src/Splat/Android/Bitmaps.cs

Currently the Jpeg compression quality is calculated by `(int)quality * 100`. The cast has higher precedence so the quality is always rounded down, in most cases resulting in a quality of 0.

Fix Jpeg quality calculation when saving Android bitmaps

---

src/Splat/Platforms/net45/Bitmaps.cs

Closes #163
Bug fix
A NullReferenceException is thrown if we use Load or LoadFromResource methods without specifying desiredHeight parameter.
It allows to use Load and LoadFromResource methods without specifying desiredHeight parameter.
Nothing

LoadBitmap even if desiredHeight is not specified

---

appveyor.yml

housekeeping
CI/CD will not work
CI/CD will work.
Nothing
This may take multiple attempts.

housekeeping: recrypt CI/CD secrets after moving repo to new github location

---

build.cake

bugfix for #159 
Attempts to publish package that isn't generated.
No longer publishes invalid packages.
Missed this in last PR as publish workflow doesn't execute until merging.

housekeeping: don't publish splat.wpf. it doesn't exist anymore

---

GitVersion.yml

Housekeeping
next-version was pinned to 3.0.0 as part of that release. This is no longer required and would have been ignored anyway. This is general cleanup.

housekeeping: unpin version number in gitversion

---

src/Directory.build.targets
src/Splat/Splat.csproj

fixes #179
drop monoandroid70 in favour of 80

feature: bump monoandroid to 8.0

---

src/Splat/Logging.cs

This is based on @kentcb work. Updated to work with latest Splat.
This also fixes #109
Adds data members to the IFullLogger to be able to tell what our current logging level is.
Not to have access to that information after access.
Have the members.
No-one really.

feature: Add support for IsXxxEnabled properties to IFullLogger

---

src/Directory.build.props

At the moment source link is not working in the project. This fixes that and matches the way Rx 4 where it does work properly.
Changes over to using the new Microsoft API sourcelink.
Use a deprecated library which no longer is supported nor works.
Use the microsoft source link which does work.
Shouldn't.

Bug Make Sourcelink use the Microsoft version.

---

src/Directory.build.targets
src/Splat/Splat.csproj

Now only compiling Android Mono 8.1

housekeeping: Update to only compile MonoAndroid 8.1

---

src/Splat/DebugLogger.cs
src/Splat/Logging.cs

Fixes #46, #58
Closes #123
As noted in #46 and #58, `DebugLogger` does not write to the debug output as `Debug.WriteLine` is stripped out in release builds of ReactiveUI.Splat. 
ASPNet Core has a DebugLogger which works, so upon investigating, it was found that by including `#define DEBUG` in the source file, the compiler does not strip out the debug only functions. So this was copied over as shown in this PR.
DebugLogger does nothing
DebugLogger writes to the debug output as intended
It *should* break nothing 😇 
**Please check if the PR …

Make DebugLogger usable by not stripping Debug.WriteLine

---

build.cmd
src/Directory.build.props
src/Splat/Platforms/Tizen/BitmapHelper.cs
src/Splat/Platforms/Tizen/Bitmaps.cs
src/Splat/Splat.csproj
src/global.json

Added the Tizen profile for the first time.
Tizen has been added to Xamarin, but it is currently not available for Tizen development with Splat.
Added a Tizen Profile to Splat to make it available to developers.
Works independently of other Profiles.
This patch includes basic Splat functionality.
However, because the implemented Tizen Profile does not allow for the image to be transformed, the options fused with it do not work.

Commit to apply Tizen to Splat for the first time

---

azure-pipelines.yml
build.cake
build.ps1
src/Directory.build.props
src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/Mocks/TextLogger.cs
src/Splat.Tests/WrappingFullLoggerTests.cs
src/Splat/Logging/DebugLogger.cs
src/Splat/Logging/IFullLogger.cs
src/Splat/Logging/ILogger.cs
src/Splat/Logging/NullLogger.cs
src/Splat/Logging/WrappingFullLogger.cs

Resolves: #186 
Currently the type is prefixed on a message string.
`ILogger` now has a method signature that takes the type.  The `WrappingFullLogger` can now call a write method that passes in the type.
Logging?

feature: Added ILogger Write method with type information

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/Logging/ActionLoggerTests.cs
src/Splat.Tests/Logging/WrappingFullLoggerTests.cs
src/Splat.Tests/Logging/WrappingPrefixLoggerTests.cs
src/Splat.Tests/Mocks/TextLogger.cs
src/Splat/Logging/ActionLogger.cs

Add a ActionLogger.
This will take delegates that the user provides.
Useful for users who want to quickly implement interfaces with their own logging systems without having the worry about implementing an entire class.

feature: add ActionLogger which takes a user given action

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/Logging/FullLoggerExtensionsTests.cs
src/Splat.Tests/Logging/WrappingFullLoggerTests.cs
src/Splat.Tests/Mocks/TextLogger.cs
src/Splat/Logging/FullLoggerExtensions.cs

This is a new feature that will allow the user to pass a Func<string> into a set of extension methods.
These Func<string> will only fire if the LogLevel of the IFullLogger is sufficient to run them. 
This allows you to avoid firing Debug logic for example when Fatal is enabled.
Inspired by the Splat.Contrib library by @dpvreony

feature: Add logger extensions that only fire when LogLevel is correct

---

src/Splat/Platforms/PlatformModeDetector.cs
src/Splat/Splat.csproj

This fixes #155 
* Added the VisualStudio.TestPlatform assemblies to our detector
* Made the detector get added to our UWP build
* Fix a bug with the Task code where it would use the TaskScheduler.Current, which is unpredictable. Now it goes off to a new task pool thread.
* The unit test checker wasn't case insensitive when it needed to be.

fix: Fix unit test detector not running on UWP

---

src/Splat/Platforms/Android/Bitmaps/DrawableBitmap.cs
src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs
src/Splat/Platforms/Android/Colors/SplatColorExtensions.cs
src/Splat/Platforms/Android/Maths/PointExtensions.cs
src/Splat/Platforms/Android/Maths/RectExtensions.cs
src/Splat/Platforms/Cocoa/Bitmaps/CocoaBitmap.cs
src/Splat/Platforms/Tizen/Bitmaps/BitmapMixins.cs
src/Splat/Platforms/Tizen/Bitmaps/TizenBitmap.cs
src/Splat/Platforms/WinRT/Bitmaps/BitmapImageBitmap.cs
src/Splat/Platforms/WinRT/Bitmaps/BitmapMixins.cs
src/Splat/Platforms/WinRT/Bitmaps/DispatcherMixin.cs
src/Splat/Platforms/WinRT/Bitmaps/PlatformBitmapLoader.cs

fixes #203 for both native and Xamarin.Forms UWP projects.
Throws an exception on the line: `var decoder = await BitmapDecoder.CreateAsync(rwStream);`
Loads the bitmap (doesn't throw an exception)
Nothing

Fix: UWP bitmap loader exception

---

build.cake
src/Splat.Autofac.Tests/DependencyResolverTests.cs
src/Splat.Autofac.Tests/Mocks/MockScreen.cs
src/Splat.Autofac.Tests/Mocks/ViewModelOne.cs
src/Splat.Autofac.Tests/Mocks/ViewModelTwo.cs
src/Splat.Autofac.Tests/Mocks/ViewOne.cs
src/Splat.Autofac.Tests/Mocks/ViewTwo.cs
src/Splat.Autofac.Tests/Splat.Autofac.Tests.csproj
src/Splat.Autofac.Tests/xunit.runner.json
src/Splat.Autofac/AutofacDependencyResolver.cs
src/Splat.Autofac/Splat.Autofac.csproj
src/Splat.Autofac/SplatAutofacExtension.cs
src/Splat.sln

- Added a AutofacDependencyResolver adapter
- Added unit tests
- Added Splat.Autofac to build.cake
Related: #233 
Adds and Autofac implementation of `IMutableDepedencyResolver` as an adapter to splat.
There is no Autofac adapter for splat.
There is an Autofac adapter for splat.
Itself?_

feature: Added Splat.Autofac

---

build.cake
src/Splat.Autofac/SplatAutofacExtensions.cs
src/Splat.SimpleInjector.Tests/DependencyResolverTests.cs
src/Splat.SimpleInjector.Tests/MockScreen.cs
src/Splat.SimpleInjector.Tests/Splat.SimpleInjector.Tests.csproj
src/Splat.SimpleInjector.Tests/View.cs
src/Splat.SimpleInjector.Tests/ViewModel.cs
src/Splat.SimpleInjector.Tests/xunit.runner.json
src/Splat.SimpleInjector/SimpleInjectorDependencyResolver.cs
src/Splat.SimpleInjector/Splat.SimpleInjector.csproj
src/Splat.SimpleInjector/SplatSimpleInjectorExtensions.cs
src/Splat.sln

Adds and Simple Injector implementation of IMutableDepedencyResolver as an adapter to splat.
There is no Simple Injector adapter for splat.
There is a Simple Injector adapter for splat.
Itself.
Simple Injector doesn't support named instances by default.  I am not sure whether we should attempt a factory implementation to provide with this feature.

feature: Added Splat.SimpleInjector

---

src/Splat.Autofac.Tests/DependencyResolverTests.cs
src/Splat.Autofac/AutofacDependencyResolver.cs

Fixes issue with Splat.Autofac not updating the container after new registrations.
Related to: #233 
It currently won't properly interact with ReactiveUI platform registrations.
The container will update correctly and resolve ReactiveUI dependencies.
Nothing.

fix: Add ContainerBuilder update to AutofacDependencyResolver

---

README.md
src/Splat.NLog/NLogLogger.cs

Fix for #245 
Adds some documentation to readme.md
Adjusting ILogger.Level changes NLog config
Back to older behaviour the ILogger manager its own level independent of NLog
none

Fix: Stop Splat.NLog adjusting loglevel config

---

src/Splat.Log4Net/Log4NetLogger.cs

Tiny tweak. Missed a change in #246 log4net level property
level property setter was still visible.
level property setter now private
nothing

bug: log4net adaptor level setter is public

---

c1e5ac01-8696-48cf-8c29-bd556f49c8a8.cake
src/Splat.Tests/Logging/FullLoggerExtensionsTests.cs
src/Splat.Tests/Logging/WrappingFullLoggerTests.cs
src/Splat.Tests/Logging/WrappingPrefixLoggerTests.cs

The mac unit tests fail due to the new line being different. They are now consistent.

housekeeping: use platform aware newlines

---

src/Splat.Serilog/SerilogFullLogger.cs
src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/Logging/AllocationFreeLoggerBaseTests.cs
src/Splat/Logging/AllocationFreeLoggerBase.cs
src/Splat/Logging/FullLoggerExtensions.cs
src/Splat/Logging/IAllocationFreeLogger.cs
src/Splat/Logging/IFullLogger.cs
src/Splat/Logging/WrappingFullLogger.cs

- Added AllocationFreeLogger interface
- Added AllocationFreeLoggerBase class
- Added AllocationFreeLoggerBase tests
- Moved methods from IFullLogger to IAllocationFreeLogger
- Removed method from WrappingFullLogger
Resolves #228 
Adds Allocation Free Logger to Splat
There are a few allocation free logger methods on the `WrappingFullLoger` and `IFullLogger` interface
There are 10 allocation free logging methods per logging type
`IFullLogger` and `WrappingFullLogger`

feature: Added Allocation Free Logging

---

src/Splat.Tests/Logging/SerilogLoggerTests.cs
src/Splat.Tests/xunit.runner.json
src/Splat/ServiceLocation/Locator.cs

We kept getting some locator tests failing still with Serilog.
Now allow for overriding so we can test the extension methods when needed against the Locator. Also now just run the tests serial in the main test project. This means you don't have contention issues on the Locator.

housekeeping: Add ability to change InternalLocator and run serial tests

---

src/Splat.Serilog/SerilogFullLogger.cs
src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/Logging/AllocationFreeLoggerBaseTests.cs
src/Splat.Tests/Logging/NLogLoggerTests.cs
src/Splat.Tests/Logging/SerilogLoggerTests.cs
src/Splat.Tests/Mocks/TextLogger.cs
src/Splat.Tests/Splat.Tests.csproj
src/Splat/Logging/AllocationFreeLoggerBase.cs
src/Splat/Logging/IAllocationFreeErrorLogger.cs
src/Splat/Logging/IFullLogger.cs
src/Splat/Logging/WrappingFullLogger.cs

Resolves #120 
There are level specific messages marked exception and the wrapping logger dictates format.
The `AllocationFreeLoggerBase` will have the ability to format the log message.
Logging?

feature: Added Allocation Free Error Logger

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/MemoizingMRUCacheTests.cs
src/Splat/Logging/DefaultLogManager.cs
src/Splat/MemoizingMRUCache.cs

This fixes #266 around threading in the MRU Cache
Wasn't thread safe.
Thread safe via ReaderWriterLockSlim
Invalidate calls the release func AFTER removing item from the cache so an exception won't leave the item in the cache in a dodgy state.
InvalidateAll has slightly different behaviour for releasing everything now.it creates new lists then clears up after releasing the lock using a temp variable.
InvalidateAll also has an option to Aggregate Exceptions (default false)
Has made MRU Cache disposable, and the DefaultLogManager.
**Please …

Fix: Thread Safety of MemoizingMRUCache 

---

src/Splat.Tests/Colors/KnownColorTests.cs
src/Splat.Tests/Colors/SplatColorTests.cs
src/Splat.Tests/TargetFrameworkExtensionsTests.cs
src/Splat.Tests/XUnitHelpers.cs
src/Splat/TargetFrameworkExtensions.cs

housekeeping for unit tests
#293 coverage has crept up, this is to push it up on the high scoring methods (according to resharper)
more tests
hopefully nothing

housekeeping: unit tests coverage

---

src/Benchmarks/CurrentBenchmark.cs
src/Benchmarks/CurrentMutableBenchmark.cs
src/Benchmarks/DependencyResolver.cs
src/Benchmarks/LocatorBenchmark.cs
src/Benchmarks/Program.cs
src/Benchmarks/Splat.Benchmarks.csproj
src/Benchmarks/Splat.Benchmarks.sln
src/Benchmarks/ViewModel.cs

Resolves: #297 
There are currently no benchmarks.
There is a Splat.Benchmarks solution for executing benchmarks.
Nothing.
** Added Benchmarks for the following**
- Locator.Current
- Locator.CurrentMutable
- Locator.RegisterResolverCallbackChanged
- Locator.SuppressResolverCallbackChangedNotifications
- Locator.AreResolverCallbackChangedNotificationsEnabled
- Locator.CurrentMutable.Register
- Locator.CurrentMutable.RegisterWithContract
- Locator.CurrentMutable.RegisterConstant
- Locator.CurrentMutable.RegisterConstantWithContract
- …

performance: Added Benchmarks

---

src/Splat.Autofac.Tests/DependencyResolverTests.cs
src/Splat.DryIoc.Tests/DependencyResolverTests.cs
src/Splat.DryIoc/DryIocDependencyResolver.cs
src/Splat.Ninject.Tests/DependencyResolverTests.cs

Resolves: #287 
- Added additional Autofac tests
- Added additional DryIoc tests
- Made DryIocDependencyResolver methods virtual
DryIoc Adapter

housekeeping: Added Splat adapter tests

---

src/Splat.Microsoft.Extensions.Logging/MicrosoftExtensionsLogProvider.cs
src/Splat.Microsoft.Extensions.Logging/MicrosoftExtensionsLoggingExtensions.cs
src/Splat.Microsoft.Extensions.Logging/MicrosoftExtensionsLoggingLogger.cs
src/Splat.Microsoft.Extensions.Logging/MsLoggingHelpers.cs
version.json

Adding a logging provider, which allows a log target to be Splat. Which will output to any of the splat logging providers.

feature: Add a MS Logging Extensions provider

---

src/Splat.Autofac/AutofacDependencyResolver.cs
src/Splat.Autofac/SplatAutofacExtensions.cs

Resolves: #302 
`UseAutofacDependencyResolver` and `AutofacDependencyResolver` take an `IContainer` instance.
`UseAutofacDependencyResolver` and `AutofacDependencyResolver` take an `IComponentContext` instance.
Splat.Autofac

feature: Use IComponentContext in Splat.Autofac

---

src/Splat.DryIoc/DryIocDependencyResolver.cs
src/Splat.DryIoc/SplatDryIocExtensions.cs

Resolves: #311 
`UseDryIocDependencyResolver` and `DryIocDependencyResolver` takes a `Container` instance.
`UseDryIocDependencyResolver` and `DryIocDependencyResolver` takes a `IContainer` instance.
Splat.DryIoc

feature: Use IContainer in Splat.DryIoc

---

src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs

Mitigates type load exceptions as described in #330
Can throw exceptions and not handled as graceful as they could be.
skip dynamic assemblies
catch exceptions, log them and return the types we did manage to load.
If dynamic assemblies are used for generating drawable resources, these will no longer load.
behaviour change that it logs out reflection type load exceptions but will continue if it can.
Needs a sense check
Also I've queried whether GetExportedTypes …

WIP: android bitmap skip dynamic and handle exceptions

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat/MemoizingMRUCache.cs

Resolves issue in https://github.com/reactiveui/ReactiveUI/issues/2081

housekeeping: Keep users from breaking with a runtime constructor change

---

src/Splat.Android.Tests/MainActivity.cs
src/Splat.Android.Tests/Resources/Resource.Designer.cs
src/Splat.Tests/Platform/PlatformBitmapLoaderTests.cs
src/Splat.Tests/Splat.Tests.csproj
src/Splat/Bitmaps/BitmapLoader.cs
src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs
src/Splat/ServiceLocation/DependencyResolverMixins.cs

resolves #330
adds capability to override the bitmap loader for a platform.
also adds netstandard2 as a test target so I could confirm bitmaploader won't compile on there.
was using reflection to load. android one also had static behaviour and if it fell over you could never retry \ override.
platformbitmaploader now uses service locator. the init logic that was in the platformbitmaploader is now in the splat resolver init.
hopefully nothing

Housekeeping: fix unit tests and the ability to override to the bitmap loader

---

README.md
src/Splat.Autofac.Tests/DependencyResolverTests.cs
src/Splat.Autofac.Tests/Splat.Autofac.Tests.csproj
src/Splat.Autofac/AutofacDependencyResolver.cs
src/Splat.DryIoc.Tests/DependencyResolverTests.cs
src/Splat.DryIoc/DryIocDependencyResolver.cs
src/Splat.Ninject/NinjectDependencyResolver.cs
src/Splat.SimpleInjector/SimpleInjectorDependencyResolver.cs
src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp3.0.approved.txt
src/Splat.Tests/ServiceLocation/BaseDependencyResolverTests.cs
src/Splat.Tests/ServiceLocation/ModernDependencyResolverTests.cs
src/Splat/ServiceLocation/DependencyResolverMixins.cs
src/Splat/ServiceLocation/FuncDependencyResolver.cs
src/Splat/ServiceLocation/IMutableDependencyResolver.cs
src/Splat/ServiceLocation/ModernDependencyResolver.cs
src/Splat/ServiceLocation/ServiceLocationInitialization.cs
version.json

Resolves #331
I've changed the splat init logic to check if the resolver it is being hooked up to has already got registrations to types we're interested in (LogManager, Logger, BitmapLoader)
depending on the nuance of the container involved. logging would be overridden or appended with no guaranteed order of retrieval.
tried to apply some consistency between dryioc and moderndependencyresolver. developers still have control within dryioc etc to get undesired behaviour. added documentation to that effect.
I've added a HasRegistration method …

feature: splat init checks for pre registrations

---

src/Splat.Tests/Splat.Tests.csproj
src/Splat/Splat.csproj

Working around an Android build issue with MsBuild.Sdk.Extras
Splat doesn't build.
Splat builds.
Nothing that isn't already broken.

fix: Android DesignTimeBuild issue with MsBuild.Sdk.Extras

---

src/Splat.Microsoft.Extensions.DependencyInjection.Tests/MicrosoftDependencyResolverTests.cs
src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs
src/Splat.Tests/ServiceLocation/BaseDependencyResolverTests.cs

Another test case with bug-fix, GetServices should never return null
`MicrosoftDependencyResolver.GetServices` returns `null` when trying to resolve a non-registered service with a contract.
It returns an empty enumerable instead.
None.

fix: Microsoft dependency injection IDependencyResolver.GetServices returns null

---

src/Splat.Autofac/AutofacDependencyResolver.cs

Fixing `AutofacDependencyResolver` so it does not throw, catch and swallow exceptions while resolving services.
I'm currently using `AutofacDependencyResolver` with `ViewModelViewHost` in a `ListView` and noticed the massive lag while debugging and the bloat of `ComponentNotRegisteredException`s being thrown even though my code works.
The new behavior should be the same, except faster when using Autofac and debugging.
Nothing I can think of.

Using TryResolve instead of Resolve with Autofac

---

src/Splat.Prism.Forms/PrismApplication.cs

Add the prism ns to allow for easy swapping in/out of PrismApplication's of different frameworks.

feature: Add prism xml:ns to PrismApplication

---

src/Splat.Microsoft.Extensions.DependencyInjection/README.md

doc update
closes #472
ms dependency injection documentation causes multiple vm initialisation by type
shows to pass through registration
nothing

#472 documentation on vm reg

---

src/Splat.Ninject.Tests/DependencyResolverTests.cs
src/Splat.Ninject/NinjectDependencyResolver.cs

Bug fix, ninject getservice no longer throws if no service registration for type.
closes #483
Throws if no registration
returns null. brings in line with moderndependencyresolver
anyone not checking for null and using try\catch.

#483 ninject now does tryget service

---

src/Splat/Logging/ConsoleLogger.cs

Bug Fix
The current format of ExceptionMessageFormat 
"{0] - {1}"
causes an error 
> System.FormatException: 'Input string was not in a correct format.'
on line 45/67: 
`Console.WriteLine(string.Format(CultureInfo.InvariantCulture, ExceptionMessageFormat, message, exception));`
**Fix**
"{0} - {1}"

Fix ExceptionMessageFormat Typo?

---

src/Splat.Microsoft.Extensions.DependencyInjection.Tests/Splat.Microsoft.Extensions.DependencyInjection.Tests.csproj
src/Splat.Ninject.Tests/DependencyResolverTests.cs
src/Splat.Ninject.Tests/NInjectDependencyResolverTests.cs
src/Splat.Ninject.Tests/Splat.Ninject.Tests.csproj
src/Splat.Ninject/NinjectDependencyResolver.cs
src/Splat.Tests/ServiceLocation/BaseDependencyResolverTests.cs

Closes #553 Ninject issue with multiple registration returning null instead of last registration
Adds the common unit tests to ninject
adds a nlog resolver test to common tests
Adds logic for contract based resolution in ninject
Adds ability for null type registration in ninject.
ninject features not on a par to other resolvers,
closes gaps in dependency resolvers
potentially any nuances\workarounds people are using in ninject

Ninject 553 last service registration and contracts

---

src/Splat.Drawing/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs

Bug fix.
`BitmapLoader.Current.Load()` throws exception `(NotSupportedException) Stream does not support writing` when load the bitmap from the `FileStream`.
No exception.
Nothing. It's flawless.

Fix an exception when loading bitmap on Android from file

---

src/Splat.Autofac.Tests/DependencyResolverTests.cs
src/Splat.Autofac.Tests/Splat.Autofac.Tests.csproj
src/Splat.Autofac/AutofacDependencyResolver.cs
src/Splat.Autofac/README.md
src/Splat.Autofac/Splat.Autofac.csproj
src/Splat.Autofac/SplatAutofacExtensions.cs
src/Splat.Tests/ServiceLocation/BaseDependencyResolverTests.cs

Raises Autofac version to 5.x in Splat.Autofac, and deprecates or removes method that mutate the container (since that is supposed to be immutable from now on).
Register method is to be used only by the ReactiveUI initialization procedure, which modifies the container by creating a child scope for each service registration.
Thanks to "skaman" for coming up with the workaround.
feature: Update Splat.Autofac to work with Autofac 5.x [#465](https://github.com/reactiveui/splat/issues/465)
Splat.Autofac is currently locked to at most 4.9.6 version.
Autofac dependency now targets version 5.x
It now (mostly) conforms to Autofac 5 container immutability. …

feature: Update Splat.Autofac to work with Autofac 5.0 (#465)

---

src/Splat.Drawing/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs

bug fix of poor perf in platform bitmap loader init during debug
closes #586
closes #421
mass debug lines on xamarin debugger means initialisation is slow and gives poor experience
uses stringbuilder and parallel assembly searching.
stringbuilder might get big, debug output is now single large burst

#586 bitmap loader init perf fixes

---

.github/workflows/ci-build.yml

Tweaks CI build to exclude more test assemblies from the coverage results
`[${{env.productNamespacePrefix}}.Tests]*,[${{env.productNamespacePrefix}}.TestRunner.*]*`
largest miss on code coverage result is Splat.Test
should move coverage result up
n/a

Housekeeping: exclude other test assemblies from coverage

---

src/Directory.build.props

Replaces FxCop with Net Analyzers to reduce the build warning spam
closes #648 
need to assess build output is like for like and adequate

housekeeping: initial replace fxcop with net analyzers

---

src/Splat.Prism.Forms/Splat.Prism.Forms.csproj
src/Splat.Prism.Tests/DependencyResolverTests.cs
src/Splat.Prism/Splat.Prism.csproj
src/Splat.Prism/SplatContainerExtension.cs

Package update
Blocks people wanting to use V8 with Splat
Updates the Splat Prism integration for the new interfaces. Still not supporting scoped objects
anyone downstream dependent on v7 but in terms of splat not much, interface was extended not broken

WIP: Housekeeping: Update Prism to V8

---

src/Splat.Common.Test/IViewModelOne.cs
src/Splat.Common.Test/MockScreen.cs
src/Splat.Common.Test/ViewModelOne.cs
src/Splat.Common.Test/ViewModelTwo.cs
src/Splat.Common.Test/ViewOne.cs
src/Splat.Common.Test/ViewTwo.cs
src/Splat.Drawing.Tests/API/ApiApprovalTests.SplatUIProject.net5.0.approved.txt
src/Splat.Drawing.Tests/API/ApiApprovalTests.SplatUIProject.netcoreapp3.1.approved.txt
src/Splat.Drawing.Tests/Colors/CoverageColorTests.cs
src/Splat.Drawing/Colors/KnownColor.cs
src/Splat.Drawing/Colors/KnownColors.cs
src/Splat.Drawing/Colors/SplatColor.cs
src/Splat.Drawing/Platforms/Cocoa/Colors/SplatColorExtensions.cs

fix
feature
tests
SplatColor == was looking at how the SplatColor was generated to compare if equal
SplatColor != was just comparing two instances directly
Now using ARGB comparision and if all are the same its equal.
the inverse of == is used for !=.
Added KnownName lookup for ARGB which will automatically convert to a KnownName generated Color if it is a match to a KnownColor.
if user was checking equal and relying on the way it was generated for comparison to be true this will no longer be true.
added a KnownColor of Empty

fix for SplatColor Equal and tests for SplatColor

---

src/ReactiveUI.DI.Tests/AutoFacReactiveUIDependencyTests.cs
src/ReactiveUI.DI.Tests/Mocks/ActivatingView.cs
src/ReactiveUI.DI.Tests/Mocks/ActivatingViewFetcher.cs
src/ReactiveUI.DI.Tests/Mocks/ActivatingViewModel.cs
src/ReactiveUI.DI.Tests/ReactiveUI.DI.Tests.csproj
src/Splat.Autofac/AutofacDependencyResolver.cs

fix
using yield to return services does not give desired results in all scenarios
removed yield to allow normal operation
none

fix #743 removed yield from AutoFac

---

src/Splat.DryIoc.Tests/DependencyResolverTests.cs
src/Splat.DryIoc/DryIocDependencyResolver.cs
src/Splat.sln

fix for #752 Keyed instances can only have a single instance so keep latest
DryIoc only allows single registrations for keyed (Contract) registrations
DryIoc currently crashes when a duplicate registration is made with contract
DryIoc now replaces the registration with the new instance
none expected as would previously throw an exception in this instance
This issue stemmed from Akavache due to a double call to Registrations Akavache.Core.Registrations which registers a default InMemory Cache and Akavache.Sqlite3.Registrations with a db Cache, both are called with the same …

fix for DryIoc - Change Append to Replace for keyed (contract) registrations

---

.github/workflows/ci-build.yml

Build fix
net6 failures due to missing openjdk
installs and runs the maui check tool that should cover installing openjdk
n/a

fix: fix CI by adding maui check

---

src/Directory.build.props

Adds support for reproducible builds as required by the .NET Foundation project requirements: https://github.com/dotnet-foundation/projects#eligibility-criteria under the Code subsection.

Add support for reproducible builds

---

CONTRIBUTING.md

closes #780 by changing references to master and develop to main
old gitflow document

housekeeping: Contributing documentation branch conventions updated

---

src/Directory.build.props

housekeeping
Builds aren't considered deterministic, so it's harder for third parties to verify the source of the package. 
The following settings are turned on
* EmbedUntrackedSources should be enabled so that compiler-generated source, like AssemblyInfo, are included in the PDB.
* ContinuousIntegrationBuild when GitHub actions are running to indicate to outside users the build was done via a CI server.
* IncludePackageReferencesDuringMarkupCompilation which will allow the Markup Compilation to know about the package references
Shouldn't break anyone.

housekeeping: Enable deterministic builds

---

.github/workflows/release.yml

fix
The build does not have  the java SDK 1.7 at the moment which is not required.
Redth's maui check tool will install Java SDK 1.7 and any other dependencies.
No-one.

housekeeping: Fix the release ci

---

src/Splat.Drawing/Platforms/ServiceLocationDrawingInitialization.cs
src/Splat.Drawing/Splat.Drawing.csproj

fix for #809 
Net5.0 and Net6.0 libraries have no targets
Added targets for Net5.0 and Net6.0 libraries
none expected

fix for Project targeting net5.0 won't build Splat.Drawing

---

src/Splat.Drawing/Platforms/Cocoa/Bitmaps/PlatformBitmapLoader.cs

fixes CI failure that is blocking PR's
missing a null check on parsed stream
null check on parsed stream
n/a

housekeeping: clean up of cocoa null ref check error in build

---

src/Splat.DryIoc.Tests/DependencyResolverTests.cs
src/Splat.DryIoc/DryIocDependencyResolver.cs

The optional `behavior` parameter is set on DryIoCs `ResolveMany` to ensure the dependencies are actually only resolved once and not every time the Enumerable resulting from the `ResolveMany` call is evaluated.
Fix #890, possibly fix #889
Dependencies are resolved as a fixed array the first time the DependencyResolver uses `ResolveMany`.

Fix DryIOC dependencies being created twice

---

.editorconfig
src/Directory.build.props
src/Directory.build.targets
src/Splat.Drawing/Platforms/WinRT/Bitmaps/PlatformBitmapLoader.cs
src/Splat.Drawing/Splat.Drawing.csproj
src/Splat.NLog/Splat.NLog.csproj
src/Splat.TestRunner.Android/Splat.TestRunner.Android.csproj
src/Splat.TestRunner.Uwp/Splat.TestRunner.Uwp.csproj
src/Splat.Tests/API/ApiApprovalTests.cs
src/Splat.Tests/Logging/WrappingFullLoggers/ConsoleLoggerTests.cs
src/Splat.Tests/Splat.Tests.csproj
src/Splat/TargetFrameworkExtensions.cs

feature
No mac catalyst
Adds mac catalyst targets
Adds net7.0 target to the version helper (not a net7 framework target)
updates some packages
No-one

feature: add mac catalyst targets

---

src/Splat.ApplicationInsights/Splat.ApplicationInsights.csproj
src/Splat.Autofac/Splat.Autofac.csproj
src/Splat.Drawing/Splat.Drawing.csproj
src/Splat.DryIoc/Splat.DryIoc.csproj
src/Splat.Exceptionless/Splat.Exceptionless.csproj
src/Splat.Log4Net/Splat.Log4Net.csproj
src/Splat.Microsoft.Extensions.DependencyInjection/Splat.Microsoft.Extensions.DependencyInjection.csproj
src/Splat.Microsoft.Extensions.Logging/MicrosoftExtensionsLoggingLogger.cs
src/Splat.Microsoft.Extensions.Logging/Splat.Microsoft.Extensions.Logging.csproj
src/Splat.NLog/Splat.NLog.csproj
src/Splat.Ninject/Splat.Ninject.csproj
src/Splat.Prism.Forms/Splat.Prism.Forms.csproj
src/Splat.Prism/Splat.Prism.csproj
src/Splat.Raygun/RaygunFeatureUsageTrackingSession.cs
src/Splat.Raygun/Splat.Raygun.csproj
src/Splat.Serilog/SerilogFullLogger.cs
src/Splat.Serilog/Splat.Serilog.csproj
src/Splat.SimpleInjector/Splat.SimpleInjector.csproj

housekeeping: Update all targets to net462, net461 no longer supported

fix: Serilog not handling null strings

---

src/Directory.build.props
src/ReactiveUI.DI.Tests/DryIocReactiveUIDependencyTests.cs
src/ReactiveUI.DI.Tests/Mocks/ActivatingView.cs
src/ReactiveUI.DI.Tests/ReactiveUI.DI.Tests.csproj
src/ReactiveUI.DI.Tests/SimpleInjectorReactiveUIDependencyTests.cs
src/ReactiveUI.DI.Tests/ViewWithViewContractThatShouldNotLoad.cs
src/Splat.Common.Test/ViewThatShouldNotLoad.cs
src/Splat.DryIoc.Tests/DependencyResolverTests.cs
src/Splat.DryIoc/DryIocDependencyResolver.cs

Closes #889, but needs a look at as it feels dirty.
It stops the instant creation of objects during registration
But it also needs to use a cast because the factory func returns object, and DryIoC throws. So there's an expression used to do the casting.
The alternative might be to break the interface and add a generic Register<T> method? (instead of the static extension that does <T> to typeof(T) and ultimately ends up as Func<object?>)
I have also removed the NullServiceType registration as I can't see a way out of any pain of using it with DryIoC.
objects registered via splat into DryIoc are instantly instantiated
Delayed creation
Usages of null …

Fix: 889 DryIoC creating instances at point of registration

---

src/Directory.build.props

update Analyser configuration
Analyser mode is set but not turned on
Analyser mode and level is set and turned on
none expected

Housekeeping Enable Analyser and Set level

---

src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet6_0.verified.txt
src/Splat.Tests/ModeDetection/ModeTests.cs
src/Splat/ModeDetection/Mode.cs

Closes #938
Add default Run and Test mode to easily override the `ModeDetector.OverrideModeDetector`

#938 Add default Run and Test mode.

---

.github/dependabot.yml

Added groupings to dependabot to reduce number of PR's being produced and to simplify the patching of groups where we need to intervene to manually group them together, or merge them in a set order.
large number of pr's for avalonia, etc.
less pr's

housekeeping: add grouping to dependabot

---

.github/dependabot.yml

Groups are currently under the github-actions portion of the supported ecosystem. Move to nuget.
Cleanup old stuff

housekeeping: Update groups

---

src/Splat.Drawing/Splat.Drawing.csproj
version.json

Update
Has outdated targets
Update targets to remove unsupported targets
users of Splat.Drawing will need to update to net7.0-xxxx

Housekeeping Update Target Frameworks

---

.github/workflows/ci-build.yml
.github/workflows/release.yml
src/Directory.build.props
src/Splat.Drawing.Tests/API/ApiApprovalTests.SplatUIProject.DotNet6_0.verified.txt
src/Splat.Drawing.Tests/BitmapLoaderTests.cs
src/Splat.Drawing.Tests/Splat.Drawing.Tests.csproj
src/Splat.Drawing/Splat.Drawing.csproj
src/Splat.SimpleInjector/Splat.SimpleInjector.csproj
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet7_0.verified.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet8_0.verified.txt
src/Splat.Tests/Splat.Tests.csproj

update
target frameworks incorrectly set to netx.0-windows
update targets to netx.0-windows10.0.17763.0 remove unsupported Android targets.

Housekeeping : Update Target Frameworks

---

.github/workflows/ci-build.yml
.github/workflows/release.yml
README.md
src/Splat.Drawing/Splat.Drawing.csproj
src/Splat.Tests/Splat.Tests.csproj
src/global.json
version.json

Update
Xamarin is supported
Retire Xamarin due to end of support in line with Microsoft
Xamarin users will need to continue using V14.8.x

Housekeeping: Retire Xamarin due to end of support

---

src/Splat.NLog/NLogLogger.cs
src/Splat.NLog/Splat.NLog.csproj
src/Splat/Logging/ILogger.cs
src/Splat/Logging/IStaticFullLogger.cs

- Minor optimization of mapping from Splat LogLevel to NLog LogLevel
- Removes dependency on System.Collections.Immutable-nuget-package
- Fixes minor spelling issue in XML docs for ILogger-interface
- Performs dictionary lookup when mapping from Splat LogLevel to NLog LogLevel
- Has additional dependency on System.Collections.Immutable-nuget-package
- Performs switch-operation when mapping from Splat LogLevel to Nlog LogLevel
- No dependency on System.Collections.Immutable-nuget-package
- No breaking changes

Splat.NLog - Faster mapping of LogLevel using switch-operation

---

src/Directory.Packages.props
src/ReactiveUI.DI.Tests/AutoFacReactiveUIDependencyTests.cs
src/ReactiveUI.DI.Tests/ReactiveUI.DI.Tests.csproj
src/Splat.Autofac.Tests/DependencyResolverTests.cs
src/Splat.Avalonia.DryIoc1.Tests/Splat.Avalonia.DryIoc1.Tests.csproj
src/Splat.Avalonia.DryIoc2.Tests/Splat.Avalonia.DryIoc2.Tests.csproj
src/Splat.Avalonia.Microsoft1.Tests/Splat.Avalonia.Microsoft1.Tests.csproj
src/Splat.Avalonia.Microsoft2.Tests/Splat.Avalonia.Microsoft2.Tests.csproj
src/Splat.Avalonia.Tests/Splat.Avalonia.Tests.csproj
src/Splat.Drawing.Tests/Splat.Drawing.Tests.csproj
src/Splat.Drawing/Platforms/ReflectionStubs.cs
src/Splat.DryIoc.Tests/DependencyResolverTests.cs
src/Splat.Prism.Tests/DependencyResolverTests.cs
src/Splat.Tests/ApplicationPerformanceMonitoring/EnableFeatureUsageTrackingExtensionsTests.cs
src/Splat.Tests/LocatorSerialRegisterTests.cs
src/Splat.Tests/LocatorTests.cs
src/Splat.Tests/Logging/StaticLoggerTests.cs
src/Splat.Tests/Logging/WrappingFullLoggers/ConsoleLoggerTests.cs
src/Splat.Tests/ServiceLocation/BaseDependencyResolverTests.cs
src/Splat.Tests/Splat.Tests.csproj

update
AOT markup found to be missing on some sections of code.
Further AOT Markup added
Trimming may occur when not expected.

Add further AOT Markup Update Packages

---

src/Splat.Tests/RectEdgeTests.cs
src/Splat.Tests/RectangleMathExtensionsTests.cs
src/Splat/Maths/RectangleMathExtensions.cs

Fix
Rectangle Math is incorrect
This pull request introduces comprehensive unit tests for `RectEdge` and `RectangleMathExtensions`, along with improvements to the `Divide` and `DivideWithPadding` methods in `RectangleMathExtensions`. The changes enhance test coverage, ensure correctness, and simplify the implementation of rectangle operations.
* **`RectEdge` Tests** (`src/Splat.Tests/RectEdgeTests.cs`):
- Added tests to validate all `RectEdge` values, their names, parsing from strings, and their behavior with the `Divide` method.
- Ensured that `RectEdge` values produce distinct results when used with `Divide`.
* **`RectangleMathExtensions` Tests** …

Fix Rectangle math

---

src/Splat.Tests/DisposableTests.cs
src/Splat/Disposables/ActionDisposable.cs
src/Splat/Disposables/CompositeDisposable.cs

update
Disposable tests are incomplete
This pull request introduces comprehensive unit tests for disposable classes and improves the robustness of the `ActionDisposable` and `CompositeDisposable` implementations by adding better validation and error handling. The most important changes include the addition of a new test suite, refactoring of `ActionDisposable` to use a traditional constructor, and improved validation for `CompositeDisposable`.
* [`src/Splat.Tests/DisposableTests.cs`](diffhunk://#diff-0b8a096b7e1e941cabd49f84b9ff03e7ee0829c41c5bb85214d1d12d5fcd09eeR1-R271): Added a new test suite for disposable classes, covering `BooleanDisposable`, `ActionDisposable`, and …

Add Disposable Tests

---

src/Splat.Autofac/Builder/AutofacSplatModule.cs
src/Splat.DryIoc/Builder/DryIocSplatModule.cs
src/Splat.Exceptionless/Builder/ExceptionlessSplatModule.cs
src/Splat.Microsoft.Extensions.DependencyInjection/Builder/MicrosoftDependencyResolverModule.cs
src/Splat.Ninject/Builder/NinjectSplatModule.cs
src/Splat.SimpleInjector/Builder/SimpleInjectorSplatModule.cs
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet8_0.verified.txt
src/Splat.Tests/API/ApiApprovalTests.SplatProject.DotNet9_0.verified.txt
src/Splat/Builder/IModule.cs
src/Splat/Builder/IReactiveUIModule.cs
src/Splat/Builder/SplatBuilderExtensions.cs

Feature
Introduces IReactiveUIModule interface and implementation modules for Autofac, DryIoc, Exceptionless, Microsoft.Extensions.DependencyInjection, Ninject, and SimpleInjector. Adds Splat Builder Extensions for applying modules to the Splat dependency resolver, enabling AOT-compatible service registration from a ReactiveUI application.
Non, separated feature.

Feature Add ReactiveUI modules and builder extensions for Splat
